# Create Tensors from Different Data Structures

Tensors are the central data type in PyTorch. In deep learning, tensors are the model's inputs, outputs, and parameters.

There are many different ways to create tensors in PyTorch.

## Task

You are given:
- A Python list named `input_list`
- A 2-dimensional NumPy array named `input_array`

Create four functions that return the following tensors:

1. A **2-dimensional tensor from the Python list**
2. A **2-dimensional tensor from the NumPy array**
3. A **tensor of shape (3,4) with all elements equal to 1**
4. A **tensor of shape (4,5) with all elements equal to 5**

In [3]:
# import MockTensor, since torch library is not supported in coderpad
from mock_tensor import MockTensor as torch

# import NumPy
import numpy as np


class Answer:

    @staticmethod
    def create_tensor_from_list(input_list):
        return torch.tensor(input_list)

    @staticmethod
    def create_tensor_from_array(input_array):
        return torch.tensor(input_array)

    @staticmethod
    def create_tensor_ones():
        return torch.ones(3, 4)

    @staticmethod
    def create_tensor_full():
        return torch.full((4, 5), 5)

ModuleNotFoundError: No module named 'mock_tensor'

In [ ]:
# This is how the code will be tested

input_list = [[1, 5, 7, 9, 11], [13, 15, 17, 19, 21]]
input_array = np.array([[[15, 17, 11], [19, 14, 13]]])

tensor_from_list = Answer.create_tensor_from_list(input_list)
tensor_from_array = Answer.create_tensor_from_array(input_array)
ones_tensor = Answer.create_tensor_ones()
full_tensor = Answer.create_tensor_full()

print("Another one solved!\n")

print("Tensor from list:", tensor_from_list)
print("Tensor from array:", tensor_from_array)
print("Ones tensor:", ones_tensor)
print("Full Tensor:", full_tensor)

Another one solved!

Tensor from list: tensor([[ 1  5  7  9 11]
 [13 15 17 19 21]])

Tensor from array: tensor([[[15 17 11]
  [19 14 13]]])

Ones tensor: tensor([[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]])

Full Tensor: tensor([[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]])