# Tensor Splitting Exercise (PyTorch-style)

In deep learning workflows, reshaping and splitting tensors is a common task.  
This exercise focuses on two popular tensor operations:

- **`chunk()`** → splits a tensor into a specified **number of equal parts**
- **`split()`** → splits a tensor according to **specified sizes**

---

## Given Tensors

- **x**: a 2D tensor with shape **(8, 5)** representing input data.
- **y**: a 1D tensor with length **16** representing labels or targets.

---

## Your Tasks

### 1. Using `chunk()`

Implement the following functions:

- **`split_x_into_chunks(x)`**  
  Split tensor **x** into **4 chunks** along its **first dimension (rows)**.

- **`split_y_into_chunks(y)`**  
  Split tensor **y** into **4 equal chunks**.

---

### 2. Using `split()`

Implement the following functions:

- **`split_x_custom(x)`**  
  Split tensor **x** into chunks containing **5 rows** and **3 rows** along its **first dimension**.

- **`split_y_custom(y)`**  
  Split tensor **y** into chunks of lengths **4**, **6**, and **6**.

---

## Expected Concepts

You will practice:

- Tensor manipulation
- Using `chunk()` for equal partitioning
- Using `split()` for custom-sized partitioning

---

## Notes

- The environment uses **`MockTensor`**, which mimics PyTorch behavior.
- Ensure the correct **dimension (`dim`)** is used when splitting multi-dimensional tensors.
- Each function should return the **result of the split operation**.

In [1]:
# import MockTensor, since torch library is not supported in coderpad
from mock_tensor import MockTensor as torch

show_expected_result = False
show_hints = False


def split_x_into_chunks(x):
    # split tensor x into 4 chunks along its 1st dimension
    return torch.chunk(x, 4, dim=0)

def split_y_into_chunks(y):
    # split tensor y into 4 equal chunks
    return torch.chunk(y, 4)

def split_x_custom(x):
    # split tensor x into chunks with 5 and 3 rows along its 1st dimension
    return torch.split(x, [5, 3], dim=0)

def split_y_custom(y):
    # split tensor y into chunks with lengths 4, 6, and 6
    return torch.split(y, [4, 6, 6])

ModuleNotFoundError: No module named 'mock_tensor'

In [ ]:
# You can edit this code to try different testing cases.
x = torch.full((8, 5), 10)
y = torch.arange(16)

split_x_into_chunks = Answer.split_x_into_chunks(x)  
split_y_into_chunks = Answer.split_y_into_chunks(y)
split_x_custom = Answer.split_x_custom(x)
split_y_custom = Answer.split_y_custom(y)

You did it! This result is exactly right.
Your code returned:
Split tensor x into 4 chunks along its 1st dimension:
 [tensor([[10 10 10 10 10]
 [10 10 10 10 10]]), tensor([[10 10 10 10 10]
 [10 10 10 10 10]]), tensor([[10 10 10 10 10]
 [10 10 10 10 10]]), tensor([[10 10 10 10 10]
 [10 10 10 10 10]])]
split tensor y into 4 chunks of equal length:
 [tensor([0 1 2 3]), tensor([4 5 6 7]), tensor([ 8  9 10 11]), tensor([12 13 14 15])]
Split tensor x into chunks with the following number of rows: 5 and 3:
 [tensor([[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]), tensor([[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]])]
Split tensor y into chunks with lengths 4, 6, and 6, respectively:
 [tensor([0 1 2 3]), tensor([4 5 6 7 8 9]), tensor([10 11 12 13 14 15])]
--- -- -- -- -- -- -- -- -- -- -- --